---
name: kcalc
confinement: strict
grade: stable
base: core20
adopt-info: kcalc
apps:
    kcalc:
        extensions:
        - kde-neon
        common-id: org.kde.kcalc.desktop
        command: usr/bin/kcalc
        plugs:
        - kde-frameworks-5-plug
slots:
    session-dbus-interface:
        interface: dbus
        name: org.kde.kcalc.desktop
        bus: session
plugs:
    kde-frameworks-5-plug:
        content: kde-frameworks-5-qt-5-15-core20-all
        interface: content
        default-provider: kde-frameworks-5-qt-5-15-core20
        target: kf5
package-repositories:
-   type: apt
    components:
    - main
    suites:
    - focal
    key-id: 444DABCF3667D0283F894EDDE6D4736255751E5D
    url: http://origin.archive.neon.kde.org/user
    key-server: keyserver.ubuntu.com
parts:
    kcalc:
        parse-info:
        - usr/share/metainfo/org.kde.kcalc.appdata.xml
        plugin: cmake
        build-packages:
        - libmpfr-dev
        - libgmp-dev
        - libkf5doctools-dev
        stage-packages:
        - libmpfr6
        - libgmp10
        source: http://download.kde.org/stable/release-service/21.04.0/src/kcalc-21.04.0.tar.xz
        cmake-parameters:
        - "-DKDE_INSTALL_USE_QT_SYS_PATHS=ON"
        - "-DCMAKE_INSTALL_PREFIX=/usr"
        - "-DCMAKE_BUILD_TYPE=Release"
        - "-DENABLE_TESTING=OFF"
        - "-DBUILD_TESTING=OFF"
        - "-DKDE_SKIP_TEST_SETTINGS=ON"
        - "-DCMAKE_FIND_ROOT_PATH=/usr\\;/root/stage\\;/snap/kde-frameworks-5-qt-5-15-core20-sdk/current"
        filesets:
            exclusion:
            - "-usr/lib/*/cmake/*"
            - "-usr/include/*"
            - "-usr/share/ECM/*"
            - "-usr/share/doc/*"
            - "-usr/share/man/*"
            - "-usr/share/icons/breeze-dark*"
            - "-usr/bin/X11"
            - "-usr/lib/gcc/x86_64-linux-gnu/6.0.0"
            - "-usr/lib/aspell/*"
        prime:
        - "$exclusion"
